const mongoose=require("mongoose");
const schema=mongoose.Schema;
const data=schema({
    name:{
        type:String
    },
    number:{
        type:Number,
        required:true,
        maxlength:10,
    },
    price:{
        type:Number
    },
    gender:{
        type:String,
        enu:["Male","Female"]  
    },
    email:{
        type:String,
        required:true
    },
    password:{
        type:String
    },
    document:{
        lic_num:{
            type:String,
            required:true
        },
        id_num:{
            type:Number,
            required:true
        }
    },
    active:{
        type:Boolean
    },
    role:{
        type:String,
        default:"driver"
    },
    loc:{
        type:String,
        required:true
    },
    order:[
        {
            type:mongoose.Schema.ObjectId,
            ref:"order"
        },
    ],
    rating:[
        {
            user:{
                type:mongoose.Schema.ObjectId,
                ref:"user"
            },
        rat:{
        type:Number
        },
        Comment:{
            type:String
        }
    }
    ],

},{timestamps:true});

const Driver=mongoose.model('driver',data);
module.exports=Driver