const drivers = [
    {
        name: "Ravi Kumar",
        number: 9876543210,
        email: "ravi.kumar@example.com",
        password: "Pass@123",
        document: { lic_num: "DL5CQ12345", id_num: 123456789012 },
        rating: [{ rate: 4, Comment: "Excellent service" }],
        active: true,
        role: 'driver',
        order: [],
        location: { type: "Point", coordinates: [77.5946, 12.9716], address: "Bangalore, Karnataka, India" }
    },
    {
        name: "Sunita Sharma",
        number: 9876543211,
        email: "sunita.sharma@example.com",
        password: "Pass@123",
        document: { lic_num: "MH12AB3456", id_num: 223456789012 },
        rating: [{ rate: 5, Comment: "Very polite" }],
        active: true,
        role: 'driver',
        order: [],
        location: { type: "Point", coordinates: [72.8777, 19.0760], address: "Mumbai, Maharashtra, India" }
    },
    {
        name: "Amit Patel",
        number: 9876543212,
        email: "amit.patel@example.com",
        password: "Pass@123",
        document: { lic_num: "GJ01CD6789", id_num: 323456789012 },
        rating: [{ rate: 3, Comment: "Average experience" }],
        active: true,
        role: 'driver',
        order: [],
        location: { type: "Point", coordinates: [72.5714, 23.0225], address: "Ahmedabad, Gujarat, India" }
    },
    {
        name: "Meena Joshi",
        number: 9876543213,
        email: "meena.joshi@example.com",
        password: "Pass@123",
        document: { lic_num: "RJ14EF1122", id_num: 423456789012 },
        rating: [{ rate: 5, Comment: "Very friendly" }],
        active: true,
        role: 'driver',
        order: [],
        location: { type: "Point", coordinates: [75.7873, 26.9124], address: "Jaipur, Rajasthan, India" }
    },
    {
        name: "Vikram Singh",
        number: 9876543214,
        email: "vikram.singh@example.com",
        password: "Pass@123",
        document: { lic_num: "PB10GH3344", id_num: 523456789012 },
        rating: [{ rate: 4, Comment: "Smooth ride" }],
        active: true,
        role: 'driver',
        order: [],
        location: { type: "Point", coordinates: [76.7794, 30.7333], address: "Chandigarh, India" }
    },
    {
        name: "Anjali Verma",
        number: 9876543215,
        email: "anjali.verma@example.com",
        password: "Pass@123",
        document: { lic_num: "UP16IJ5566", id_num: 623456789012 },
        rating: [{ rate: 5, Comment: "Very helpful" }],
        active: true,
        role: 'driver',
        order: [],
        location: { type: "Point", coordinates: [77.3910, 28.5355], address: "Noida, Uttar Pradesh, India" }
    },
    {
        name: "Rohit Chatterjee",
        number: 9876543216,
        email: "rohit.chatterjee@example.com",
        password: "Pass@123",
        document: { lic_num: "WB20KL7788", id_num: 723456789012 },
        rating: [{ rate: 4, Comment: "Quick service" }],
        active: true,
        role: 'driver',
        order: [],
        location: { type: "Point", coordinates: [88.3639, 22.5726], address: "Kolkata, West Bengal, India" }
    },
    {
        name: "Pooja Desai",
        number: 9876543217,
        email: "pooja.desai@example.com",
        password: "Pass@123",
        document: { lic_num: "GA03MN9900", id_num: 823456789012 },
        rating: [{ rate: 5, Comment: "Very clean car" }],
        active: true,
        role: 'driver',
        order: [],
        location: { type: "Point", coordinates: [73.8278, 15.4909], address: "Panaji, Goa, India" }
    },
    {
        name: "Manoj Nair",
        number: 9876543218,
        email: "manoj.nair@example.com",
        password: "Pass@123",
        document: { lic_num: "KL07OP1234", id_num: 923456789012 },
        rating: [{ rate: 4, Comment: "Very professional" }],
        active: true,
        role: 'driver',
        order: [],
        location: { type: "Point", coordinates: [76.2673, 9.9312], address: "Kochi, Kerala, India" }
    },
    {
        name: "Divya Reddy",
        number: 9876543219,
        email: "divya.reddy@example.com",
        password: "Pass@123",
        document: { lic_num: "AP09QR5678", id_num: 103456789012 },
        rating: [{ rate: 5, Comment: "Highly recommended" }],
        active: true,
        role: 'driver',
        order: [],
        location: { type: "Point", coordinates: [78.4867, 17.3850], address: "Hyderabad, Telangana, India" }
    },
    {
        name: "Karan Mehta",
        number: 9876543220,
        email: "karan.mehta@example.com",
        password: "Pass@123",
        document: { lic_num: "HR26ST4321", id_num: 113456789012 },
        rating: [{ rate: 3, Comment: "Okay ride" }],
        active: true,
        role: 'driver',
        order: [],
        location: { type: "Point", coordinates: [77.1025, 28.7041], address: "Delhi, India" }
    },
    {
        name: "Neha Kulkarni",
        number: 9876543221,
        email: "neha.kulkarni@example.com",
        password: "Pass@123",
        document: { lic_num: "MH14UV3456", id_num: 123456780012 },
        rating: [{ rate: 5, Comment: "Punctual driver" }],
        active: true,
        role: 'driver',
        order: [],
        location: { type: "Point", coordinates: [73.8567, 18.5204], address: "Pune, Maharashtra, India" }
    },
    {
        name: "Suresh Babu",
        number: 9876543222,
        email: "suresh.babu@example.com",
        password: "Pass@123",
        document: { lic_num: "TN01WX5678", id_num: 133456789012 },
        rating: [{ rate: 4, Comment: "Good driving" }],
        active: true,
        role: 'driver',
        order: [],
        location: { type: "Point", coordinates: [80.2707, 13.0827], address: "Chennai, Tamil Nadu, India" }
    },
    {
        name: "Lalita Devi",
        number: 9876543223,
        email: "lalita.devi@example.com",
        password: "Pass@123",
        document: { lic_num: "BR01XY7890", id_num: 143456789012 },
        rating: [{ rate: 5, Comment: "Very kind" }],
        active: true,
        role: 'driver',
        order: [],
        location: { type: "Point", coordinates: [85.1376, 25.5941], address: "Patna, Bihar, India" }
    },
    {
        name: "Rajesh Gupta",
        number: 9876543224,
        email: "rajesh.gupta@example.com",
        password: "Pass@123",
        document: { lic_num: "MP09ZA9876", id_num: 153456789012 },
        rating: [{ rate: 4, Comment: "Smooth experience" }],
        active: true,
        role: 'driver',
        order: [],
        location: { type: "Point", coordinates: [75.8577, 22.7196], address: "Indore, Madhya Pradesh, India" }
    }
];
